#!/bin/bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
	echo 'Utilisation :'
	echo 'playlist-dl'
	echo 'playlist-dl [PLAYLIST URL]'
	exit 1
fi


if [ $# -eq 1 ]
then
	python3 /data/data/com.termux/files/home/storage/shared/Documents/playlist-dl/playlist-dl.py $1
elif [ $# -eq 0 ]
then
	python3 /data/data/com.termux/files/home/storage/shared/Documents/playlist-dl/playlist-dl.py
else
	echo 'There can be at most one argument'
	echo 'Use -h or --help for help'
fi

exit 1
